[project]
name = "brainbay"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.133.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "ollama>=0.6.1",
    "uvicorn>=0.41.0",
]
